### ISSUE TITLE
两个字段都为null，会被判定为不匹配

### ISSUE THREAD

**Issue by jiaojiaoshiny** [codeleep/json-diff#16]
{
            "illustrate": "The expect('null') data is inconsistent with the actual('null') data",  =====》预期值和实际值都是null，应该判定为匹配
            "travelPath": {
                "abstractTravelPath": "$.result.mobileRichText",
                "actualTravelPath": "$.result.mobileRichText",
                "expectTravelPath": "$.result.mobileRichText"
            }
        },

**Comment by codeleep** [comment]
这个在最新版已经被修复。可以升级到4.1.4解决

**Comment by himdd** [comment]
升级到最新版本后，并没有修复哈 
    <dependency>
      <groupId>cn.xiaoandcai</groupId>
      <artifactId>json-diff</artifactId>
      <version>4.1.4-RC1-RELEASE</version>
  </dependency>
